name: flutter_spinning_wheel
description: A customizable widget to use as a spinning wheel in Flutter.
version: 1.1.0
homepage: https://github.com/davidanaya/flutter-spinning-wheel
repository: https://github.com/davidanaya/flutter-spinning-wheel
issue_tracker: https://github.com/davidanaya/flutter-spinning-wheel/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
